package assets

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"rotor/internal/luau/cst"
)

func demoLock() *Lockfile {
	l := NewLockfile()
	l.Assets["assets/logo.png"] = LockEntry{Hash: "sha256:1", AssetID: 111}
	l.Assets["assets/sounds/hit.ogg"] = LockEntry{Hash: "sha256:2", AssetID: 222}
	l.Assets["assets/sounds/my-sound v2.mp3"] = LockEntry{Hash: "sha256:3", AssetID: 333}
	l.Assets["assets/end.png"] = LockEntry{Hash: "sha256:4", AssetID: 444}
	return l
}

const wantLuau = `-- generated by rotor asset sync; do not edit
return {
	_end = "rbxassetid://444",
	logo = "rbxassetid://111",
	sounds = {
		hit = "rbxassetid://222",
		mySoundV2 = "rbxassetid://333",
	},
}
`

const wantTypes = `// generated by rotor asset sync; do not edit
declare const assets: {
	readonly _end: string;
	readonly logo: string;
	readonly sounds: {
		readonly hit: string;
		readonly mySoundV2: string;
	};
};
export = assets;
`

func TestGenerateLuauGolden(t *testing.T) {
	got, err := GenerateLuau(demoLock())
	if err != nil {
		t.Fatal(err)
	}
	if got != wantLuau {
		t.Fatalf("luau output:\n%s\nwant:\n%s", got, wantLuau)
	}
	// The generated module must parse cleanly with rotor's own Luau parser.
	_, diags := cst.Parse(got)
	if len(diags) != 0 {
		t.Fatalf("generated luau has %d parse diagnostics: %+v", len(diags), diags)
	}
}

func TestGenerateTypesGolden(t *testing.T) {
	got, err := GenerateTypes(demoLock())
	if err != nil {
		t.Fatal(err)
	}
	if got != wantTypes {
		t.Fatalf("d.ts output:\n%s\nwant:\n%s", got, wantTypes)
	}
}

func TestGenerateEmptyLockfile(t *testing.T) {
	luau, err := GenerateLuau(NewLockfile())
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(luau, "return {}") {
		t.Fatalf("empty luau module: %q", luau)
	}
	if _, diags := cst.Parse(luau); len(diags) != 0 {
		t.Fatalf("empty luau module has diagnostics: %+v", diags)
	}
	dts, err := GenerateTypes(NewLockfile())
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(dts, "declare const assets: {};") {
		t.Fatalf("empty d.ts: %q", dts)
	}
}

func TestGenerateNoSharedRootKeepsTopSegments(t *testing.T) {
	l := NewLockfile()
	l.Assets["images/a.png"] = LockEntry{Hash: "h", AssetID: 1}
	l.Assets["sounds/b.ogg"] = LockEntry{Hash: "h", AssetID: 2}
	got, err := GenerateLuau(l)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(got, "images = {") || !strings.Contains(got, "sounds = {") {
		t.Fatalf("mixed roots must keep their top segments:\n%s", got)
	}

	// A top-level file alongside a shared dir also prevents stripping.
	l2 := NewLockfile()
	l2.Assets["assets/a.png"] = LockEntry{Hash: "h", AssetID: 1}
	l2.Assets["root.png"] = LockEntry{Hash: "h", AssetID: 2}
	got2, err := GenerateLuau(l2)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(got2, "assets = {") || !strings.Contains(got2, "root = ") {
		t.Fatalf("unexpected tree:\n%s", got2)
	}
}

func TestGenerateCollisionsError(t *testing.T) {
	// Two files mapping to the same identifier.
	l := NewLockfile()
	l.Assets["assets/logo.png"] = LockEntry{Hash: "h", AssetID: 1}
	l.Assets["assets/logo.jpg"] = LockEntry{Hash: "h", AssetID: 2}
	if _, err := GenerateLuau(l); err == nil || !strings.Contains(err.Error(), "logo") {
		t.Fatalf("want a collision error naming \"logo\", got %v", err)
	}

	// A file and a folder mapping to the same identifier.
	l2 := NewLockfile()
	l2.Assets["assets/sounds.png"] = LockEntry{Hash: "h", AssetID: 1}
	l2.Assets["assets/sounds/hit.ogg"] = LockEntry{Hash: "h", AssetID: 2}
	if _, err := GenerateLuau(l2); err == nil || !strings.Contains(err.Error(), "sounds") {
		t.Fatalf("want a file/folder collision error, got %v", err)
	}
}

func TestSanitizeIdent(t *testing.T) {
	cases := []struct {
		in, want string
		wantErr  bool
	}{
		{in: "logo", want: "logo"},
		{in: "my-logo", want: "myLogo"},
		{in: "hit sound", want: "hitSound"},
		{in: "snake_case_name", want: "snakeCaseName"},
		{in: "Already-Camel", want: "AlreadyCamel"},
		{in: "v2", want: "v2"},
		{in: "2fast", want: "_2fast"},
		{in: "end", want: "_end"},
		{in: "while", want: "_while"},
		{in: "weird!!name", want: "weirdName"},
		{in: "--leading", want: "leading"},
		{in: "trailing--", want: "trailing"},
		{in: "continue", want: "continue"}, // contextual in Luau, not reserved
		{in: "!!!", wantErr: true},
		{in: "", wantErr: true},
	}
	for _, c := range cases {
		got, err := sanitizeIdent(c.in)
		if c.wantErr {
			if err == nil {
				t.Errorf("sanitizeIdent(%q) = %q, want error", c.in, got)
			}
			continue
		}
		if err != nil {
			t.Errorf("sanitizeIdent(%q): %v", c.in, err)
			continue
		}
		if got != c.want {
			t.Errorf("sanitizeIdent(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestWriteOutputsAtomicWithParents(t *testing.T) {
	dir := t.TempDir()
	lock := demoLock()
	if err := WriteOutputs(dir, "src/shared/assets.luau", "src/shared/assets.d.ts", lock); err != nil {
		t.Fatal(err)
	}
	luau, err := os.ReadFile(filepath.Join(dir, "src", "shared", "assets.luau"))
	if err != nil {
		t.Fatal(err)
	}
	if string(luau) != wantLuau {
		t.Fatalf("written luau differs:\n%s", luau)
	}
	dts, err := os.ReadFile(filepath.Join(dir, "src", "shared", "assets.d.ts"))
	if err != nil {
		t.Fatal(err)
	}
	if string(dts) != wantTypes {
		t.Fatalf("written d.ts differs:\n%s", dts)
	}
	// Overwrite is fine and leaves no temp litter.
	if err := WriteOutputs(dir, "src/shared/assets.luau", "src/shared/assets.d.ts", lock); err != nil {
		t.Fatal(err)
	}
	entries, err := os.ReadDir(filepath.Join(dir, "src", "shared"))
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 2 {
		t.Fatalf("expected 2 files, got %d", len(entries))
	}
}
