# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: rotor

builds:
  - id: rotor
    main: ./cmd/rotor
    binary: rotor
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: rotor
    ids:
      - rotor
    name_template: "rotor-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "rotor-v{{ .Version }}-checksums.txt"

release:
  github:
    owner: uproot
    name: rotor
  prerelease: auto

changelog:
  disable: true
