package compile

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ----------------------------------------------------------------------------
// $env compile-time environment macro — rotor extension (no rbxtsc
// counterpart; replaces the community rbxts-transform-env plugin).
//
// The fixture deliberately does NOT declare `$env` in its globals.d.ts: the
// type surface must come from the synthetic in-memory __rotor_env.d.ts that
// newProjectProgramFromFS injects (envdecl.go), so this test covers both the
// declaration injection and the transformer inlining (envmacro.go).
//
// Value resolution priority (internal/dotenv): process env >
// .env.<NODE_ENV> > .env, with NODE_ENV itself resolved from the process
// env first, then .env.
// ----------------------------------------------------------------------------

func TestEnvMacroModel(t *testing.T) {
	// MUST be set before compiling: $env inlines at transform time.
	t.Setenv("ROTOR_TEST_ENV_PROC", "from-process") // overrides the .env value "from-file"
	t.Setenv("NODE_ENV", "studio")                  // selects .env.studio (OVERLAY=from-studio)

	files := compileRuntimeLibProject(t, "env_model")

	// In order: .env value; process-env override; fallback arg; unset -> nil;
	// dot access; element access; 2-arity with a set name (fallback unused);
	// .env.<NODE_ENV> override; double/single quote stripping.
	want := "-- Compiled with roblox-ts v3.0.0\n" +
		"print(\"Adventure Quest\")\n" +
		"print(\"from-process\")\n" +
		"print(\"fallback-value\")\n" +
		"print(nil)\n" +
		"print(\"Adventure Quest\")\n" +
		"print(\"Adventure Quest\")\n" +
		"print(\"Adventure Quest\")\n" +
		"print(\"from-studio\")\n" +
		"print(\"hello world\")\n" +
		"print(\"single quoted\")\n" +
		"return nil\n"
	if got := files["out/main.luau"]; got != want {
		t.Errorf("out/main.luau:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

// A non-literal $env argument cannot be inlined at compile time and must
// produce a clear rotor diagnostic — never a panic (which would surface as
// an "internal compiler error").
func TestEnvMacroNonLiteralArgDiagnostic(t *testing.T) {
	text, diags, err := CompileFileDetailed(filepath.Join("testdata", "env_diag_model"), "src/main.ts")
	if err != nil {
		t.Fatalf("CompileFileDetailed returned hard error (want diagnostic): %v", err)
	}
	if text != "" {
		t.Errorf("expected no output text, got:\n%s", text)
	}
	found := false
	for _, d := range diags {
		if d.Code == "rotorEnvNonLiteralArg" {
			found = true
			if !strings.Contains(d.Message, "string literal") {
				t.Errorf("diagnostic message not descriptive: %q", d.Message)
			}
		}
	}
	if !found {
		t.Errorf("diagnostics = %+v, want one with code rotorEnvNonLiteralArg", diags)
	}
}

// WriteEnvDeclarations is the on-disk editor companion writer: missing →
// written, stale → rewritten, current → untouched. The file must carry
// EXACTLY the synthetic declaration (plus the generated-file header) so the
// compiler can treat the two as interchangeable.
func TestWriteEnvDeclarations(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, EnvDeclFileName)

	wrote, err := WriteEnvDeclarations(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !wrote {
		t.Error("missing file: wrote = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != EnvDeclFileText {
		t.Error("written content differs from EnvDeclFileText")
	}
	// Parity guard: the on-disk file and the synthetic in-memory file must
	// contain the identical declaration body.
	if !strings.Contains(string(data), envDeclBody) || !strings.Contains(envDeclText, envDeclBody) {
		t.Error("on-disk and synthetic declarations no longer share the same body")
	}
	if !strings.Contains(string(data), "Generated by rotor; do not edit") {
		t.Error("on-disk declaration is missing the generated-file header")
	}

	// current → untouched
	if wrote, err = WriteEnvDeclarations(dir); err != nil || wrote {
		t.Errorf("up-to-date file: wrote = %v, err = %v; want false, nil", wrote, err)
	}

	// stale → rewritten
	if err := os.WriteFile(path, []byte("// stale\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if wrote, err = WriteEnvDeclarations(dir); err != nil || !wrote {
		t.Errorf("stale file: wrote = %v, err = %v; want true, nil", wrote, err)
	}
}

// A $env-using project built through the disk-writing pipeline must gain the
// rotor-env.d.ts editor companion (and report the macro usage on the result);
// a project that never mentions $env must NOT gain the file.
func TestBuildWritesEnvTypesForEnvProjects(t *testing.T) {
	t.Run("env project", func(t *testing.T) {
		dir := t.TempDir()
		copyDir(t, filepath.Join("testdata", "env_model"), dir)

		result, diags, err := BuildProjectWithOptions(dir, ProjectOptions{})
		if err != nil {
			t.Fatalf("build failed: %v\n%s", err, strings.Join(diags, "\n"))
		}
		if !result.UsesEnvMacro {
			t.Error("UsesEnvMacro = false, want true")
		}
		if !result.WroteEnvTypes {
			t.Error("WroteEnvTypes = false, want true on first build")
		}
		data, err := os.ReadFile(filepath.Join(dir, EnvDeclFileName))
		if err != nil {
			t.Fatalf("rotor-env.d.ts not written: %v", err)
		}
		if string(data) != EnvDeclFileText {
			t.Error("rotor-env.d.ts content differs from EnvDeclFileText")
		}

		// Second build: file is current, no rewrite.
		result, diags, err = BuildProjectWithOptions(dir, ProjectOptions{})
		if err != nil {
			t.Fatalf("rebuild failed: %v\n%s", err, strings.Join(diags, "\n"))
		}
		if !result.UsesEnvMacro || result.WroteEnvTypes {
			t.Errorf("rebuild: UsesEnvMacro = %v, WroteEnvTypes = %v; want true, false",
				result.UsesEnvMacro, result.WroteEnvTypes)
		}
	})

	t.Run("non-env project", func(t *testing.T) {
		dir := t.TempDir()
		copyDir(t, filepath.Join("testdata", "env_model"), dir)
		// Replace the only source file with one that never mentions the macro.
		if err := os.WriteFile(filepath.Join(dir, "src", "main.ts"), []byte("print(1);\n"), 0o644); err != nil {
			t.Fatal(err)
		}

		result, diags, err := BuildProjectWithOptions(dir, ProjectOptions{})
		if err != nil {
			t.Fatalf("build failed: %v\n%s", err, strings.Join(diags, "\n"))
		}
		if result.UsesEnvMacro || result.WroteEnvTypes {
			t.Errorf("UsesEnvMacro = %v, WroteEnvTypes = %v; want false, false",
				result.UsesEnvMacro, result.WroteEnvTypes)
		}
		if _, err := os.Stat(filepath.Join(dir, EnvDeclFileName)); err == nil {
			t.Error("rotor-env.d.ts written for a project that never references $env")
		}
	})
}

// Coexistence parity guard: a project that carries the generated on-disk
// rotor-env.d.ts in its program (tsconfig include) AND uses $env must compile
// without a duplicate-identifier error — the injector skips the synthetic
// declaration when the identical on-disk one is already a root file — and
// must produce byte-identical output to the same project without the file.
func TestEnvMacroCoexistsWithOnDiskDeclaration(t *testing.T) {
	t.Setenv("ROTOR_TEST_ENV_PROC", "from-process")
	t.Setenv("NODE_ENV", "studio")

	baseline := compileRuntimeLibProject(t, "env_model")

	dir := t.TempDir()
	copyDir(t, filepath.Join("testdata", "env_model"), dir)
	if _, err := WriteEnvDeclarations(dir); err != nil {
		t.Fatal(err)
	}
	tsconfigPath := filepath.Join(dir, "tsconfig.json")
	tsconfig, err := os.ReadFile(tsconfigPath)
	if err != nil {
		t.Fatal(err)
	}
	patched := strings.Replace(string(tsconfig), `"include": ["src"]`, `"include": ["src", "rotor-env.d.ts"]`, 1)
	if patched == string(tsconfig) {
		t.Fatal("fixture tsconfig include not found to patch")
	}
	if err := os.WriteFile(tsconfigPath, []byte(patched), 0o644); err != nil {
		t.Fatal(err)
	}

	files, diags, err := CompileProject(dir)
	if err != nil {
		t.Fatalf("coexistence compile failed (duplicate $env declaration?): %v\n%s", err, strings.Join(diags, "\n"))
	}
	if files["out/main.luau"] != baseline["out/main.luau"] {
		t.Errorf("output with on-disk rotor-env.d.ts differs from baseline:\ngot:\n%s\nwant:\n%s",
			files["out/main.luau"], baseline["out/main.luau"])
	}
}

// A bare `$env` outside call/property/element position (e.g. aliasing it)
// has no runtime value to emit — also a diagnostic, not a panic.
func TestEnvMacroBareUsageDiagnostic(t *testing.T) {
	text, diags, err := CompileFileDetailed(filepath.Join("testdata", "env_diag_model"), "src/bare.ts")
	if err != nil {
		t.Fatalf("CompileFileDetailed returned hard error (want diagnostic): %v", err)
	}
	if text != "" {
		t.Errorf("expected no output text, got:\n%s", text)
	}
	found := false
	for _, d := range diags {
		if d.Code == "rotorEnvBadUsage" {
			found = true
		}
	}
	if !found {
		t.Errorf("diagnostics = %+v, want one with code rotorEnvBadUsage", diags)
	}
}
