package compile

import (
	"os"
	"path/filepath"
	"strings"

	"rotor/tsgo/tspath"
	"rotor/tsgo/vfs"
	"rotor/tsgo/vfs/wrapvfs"
)

// Synthetic ambient declaration for the four rotor compile-time stamping/
// introspection macros — SUPERSET extensions with no rbxtsc counterpart (see
// internal/transformer/{nameofmacro,keysmacro,filemacro,gitmacro}.go). One
// shared declaration covers all of them, injected exactly like the $env and
// $asset declarations (envdecl.go / assetdecl.go), with the same coexistence
// guard so a project carrying the generated on-disk companion does not collide
// with the in-memory one.
//
// Parity safety: identical to envdecl.go's rationale — the file is a declaration
// file (excluded from compiled sources and CommonSourceDirectory), appended
// AFTER the config-derived root files, global under moduleDetection:"force",
// and code that never mentions these macros resolves no differently. They did
// not compile under rbxtsc (undeclared identifiers), so inlining them is a
// strict superset.
const macroDeclFileName = "__rotor_macros.d.ts"

// macroDeclBody is the one true declaration for the four macros. The synthetic
// in-memory file (macroDeclText) and the generated on-disk editor companion
// (MacroDeclFileText) must carry EXACTLY this declaration so the two are
// interchangeable — only their leading comments differ.
const macroDeclBody = `declare function $nameof(item: unknown): string;
declare function $keys<T>(): string[];
declare function $file(path: string): any;
declare function $git(field: "sha" | "branch" | "tag"): string;
declare function $git(field: "dirty"): boolean;
declare function $buildTime(): string;
`

const macroDeclText = `// rotor compiler extension (synthetic, in-memory): the $nameof, $keys, $file,
// $git, and $buildTime compile-time macros. This file is injected by the rotor
// compiler and does not exist on disk.
` + macroDeclBody

// MacroDeclFileName is the on-disk editor companion for the four macros. rotor
// writes it into the project root (rotor build / rotor check refresh it when the
// project references any of these macros) so editors that never see the
// synthetic in-memory declaration still type-check them.
const MacroDeclFileName = "rotor-macros.d.ts"

// MacroDeclFileText is the content of the on-disk rotor-macros.d.ts: a
// generated-file header plus exactly the same declarations the compiler injects.
const MacroDeclFileText = `// Generated by rotor; do not edit. This file is refreshed automatically.
// Editor types for rotor's $nameof / $keys / $file / $git / $buildTime
// compile-time macros. The compiler injects identical declarations in-memory,
// so this file exists purely for editors/IDEs (add it to tsconfig "include" if
// your editor does not pick it up). See docs.md ("rotor extensions").
` + macroDeclBody

// macroDeclSubstrings are the cheap substring sentinels used to detect whether
// any project source references one of the four macros (the same kind of scan
// build/check use for $env / $asset). A hit on any one drives the on-disk
// rotor-macros.d.ts refresh.
var macroDeclSubstrings = []string{"$nameof", "$keys", "$file", "$git", "$buildTime"}

// SourceUsesMacros reports whether text references any of the four macros.
func SourceUsesMacros(text string) bool {
	for _, sub := range macroDeclSubstrings {
		if strings.Contains(text, sub) {
			return true
		}
	}
	return false
}

// WriteMacroDeclarations writes rotor-macros.d.ts into projectDir when it is
// missing or stale (content differs from MacroDeclFileText). The write is
// atomic (temp file + rename). Reports whether the file was (re)written.
func WriteMacroDeclarations(projectDir string) (bool, error) {
	path := filepath.Join(projectDir, MacroDeclFileName)
	if existing, err := os.ReadFile(path); err == nil && string(existing) == MacroDeclFileText {
		return false, nil
	}
	if err := atomicWriteFile(path, []byte(MacroDeclFileText)); err != nil {
		return false, err
	}
	return true, nil
}

// projectDeclaresMacrosOnDisk reports whether the parsed program's root files
// already include an on-disk rotor-macros.d.ts that declares these macros. When
// they do, the synthetic in-memory declaration must NOT also be appended — two
// global declarations of the same function would be a duplicate-identifier
// error. The content check is tolerant (any `declare function $nameof`).
func projectDeclaresMacrosOnDisk(fs vfs.FS, fileNames []string) bool {
	for _, name := range fileNames {
		base := name
		if i := strings.LastIndexByte(name, '/'); i >= 0 {
			base = name[i+1:]
		}
		if !strings.EqualFold(base, MacroDeclFileName) {
			continue
		}
		if text, ok := fs.ReadFile(name); ok && strings.Contains(text, "declare function $nameof") {
			return true
		}
	}
	return false
}

// macroDeclPath places the synthetic declaration next to the tsconfig (slash
// separated, like all vfs paths).
func macroDeclPath(configPath string) string {
	return tspath.GetDirectoryPath(configPath) + "/" + macroDeclFileName
}

// injectMacroDeclFS wraps fs so the synthetic declaration file exists at
// declPath. Same two-interception shape as injectEnvDeclFS / injectAssetDeclFS.
func injectMacroDeclFS(inner vfs.FS, declPath string) vfs.FS {
	matches := func(path string) bool {
		if inner.UseCaseSensitiveFileNames() {
			return path == declPath
		}
		return strings.EqualFold(path, declPath)
	}
	return wrapvfs.Wrap(inner, wrapvfs.Replacements{
		FileExists: func(path string) bool {
			return matches(path) || inner.FileExists(path)
		},
		ReadFile: func(path string) (string, bool) {
			if matches(path) {
				return macroDeclText, true
			}
			return inner.ReadFile(path)
		},
	})
}
