package compile

import (
	"os"
	"path/filepath"
)

// One consolidated on-disk editor companion — rotor.d.ts — declaring ALL of
// rotor's compile-time macros ($env, $asset, $nameof, $keys, $file, $git,
// $buildTime). It supersedes the former per-macro split (rotor-env.d.ts /
// rotor-asset.d.ts / rotor-macros.d.ts): rotor init scaffolds it, and
// rotor build / rotor check / rotor asset refresh it whenever a project
// references any macro, so editors type-check every macro from a single file.
//
// The compiler still injects each macro's synthetic declaration in-memory
// (envdecl.go / assetdecl.go / macrodecl.go); this file is purely for
// editors/IDEs that never see those synthetic copies. The coexistence guards
// (projectDeclares*OnDisk) recognise rotor.d.ts and skip the synthetic
// injection for any macro it already declares, so a project that lists
// rotor.d.ts in its tsconfig "include" never hits a duplicate-identifier error.
const RotorTypesFileName = "rotor.d.ts"

// rotorTypesBody concatenates the three synthetic declaration bodies verbatim
// (blank-line separated) so the on-disk companion and the in-memory injections
// stay byte-for-byte interchangeable — a parity test asserts each body appears.
const rotorTypesBody = envDeclBody + "\n" + assetDeclBody + "\n" + macroDeclBody

// RotorTypesFileText is the content of the on-disk rotor.d.ts: a generated-file
// header plus exactly the same declarations the compiler injects.
const RotorTypesFileText = `// Generated by rotor; do not edit. This file is refreshed automatically.
// Editor types for rotor's compile-time macros: $env, $asset, $nameof, $keys,
// $file, $git, and $buildTime. The compiler injects identical declarations
// in-memory, so this file exists purely for editors/IDEs (the scaffolded
// tsconfig lists it under "include"). See docs.md ("rotor extensions").
` + rotorTypesBody

// WriteRotorTypes writes rotor.d.ts into projectDir when it is missing or stale
// (content differs from RotorTypesFileText). The write is atomic (temp file +
// rename, via atomicWriteFile in envdecl.go). Reports whether it was (re)written.
func WriteRotorTypes(projectDir string) (bool, error) {
	path := filepath.Join(projectDir, RotorTypesFileName)
	if existing, err := os.ReadFile(path); err == nil && string(existing) == RotorTypesFileText {
		return false, nil
	}
	if err := atomicWriteFile(path, []byte(RotorTypesFileText)); err != nil {
		return false, err
	}
	return true, nil
}
