package compile

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// WriteRotorTypes is the single on-disk editor companion writer for ALL of
// rotor's compile-time macros: missing → written, stale → rewritten, current →
// untouched. The file must carry EXACTLY the synthetic declaration bodies (plus
// the generated-file header) so the compiler treats the on-disk and in-memory
// declarations as interchangeable.
func TestWriteRotorTypes(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, RotorTypesFileName)

	wrote, err := WriteRotorTypes(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !wrote {
		t.Error("missing file: wrote = false, want true")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != RotorTypesFileText {
		t.Error("written content differs from RotorTypesFileText")
	}

	// One file, every macro: $env, $asset, $nameof, $keys, $file, $git, $buildTime.
	for _, want := range []string{
		"declare const $env",
		"declare function $asset(",
		"declare function $nameof(",
		"declare function $keys<",
		"declare function $file(",
		"declare function $git(",
		"declare function $buildTime(",
	} {
		if !strings.Contains(string(data), want) {
			t.Errorf("rotor.d.ts missing declaration %q", want)
		}
	}
	// Parity guard: each synthetic in-memory body must appear verbatim, so the
	// on-disk companion and the injected declarations never diverge.
	for _, body := range []string{envDeclBody, assetDeclBody, macroDeclBody} {
		if !strings.Contains(string(data), body) {
			t.Error("rotor.d.ts no longer contains a synthetic declaration body verbatim")
		}
	}
	if !strings.Contains(string(data), "Generated by rotor; do not edit") {
		t.Error("rotor.d.ts is missing the generated-file header")
	}

	// current → untouched
	if wrote, err = WriteRotorTypes(dir); err != nil || wrote {
		t.Errorf("up-to-date file: wrote = %v, err = %v; want false, nil", wrote, err)
	}

	// stale → rewritten
	if err := os.WriteFile(path, []byte("// stale\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if wrote, err = WriteRotorTypes(dir); err != nil || !wrote {
		t.Errorf("stale file: wrote = %v, err = %v; want true, nil", wrote, err)
	}
}
