package config

import (
	"os"
	"path/filepath"
)

// TypeDeclarationsFileName is the file WriteTypeDeclarations writes.
const TypeDeclarationsFileName = "rotor-config.d.ts"

// TypeDeclarations is the ambient TypeScript declaration for the virtual
// "rotor/config" module. It mirrors the Go structs in config.go 1:1 and is
// what gives rotor.config.ts editor typing (written by `rotor init`,
// refreshed by any command when stale).
const TypeDeclarations = `// Generated by rotor. Do not edit; this file is refreshed automatically.
// Ambient types for the virtual "rotor/config" module used by rotor.config.ts.

declare module "rotor/config" {
	/** Where generated asset modules are written. */
	export interface AssetsOutput {
		/** Output path of the generated Luau module, e.g. "src/shared/assets.luau". */
		luau?: string;
		/** Output path of the matching .d.ts, e.g. "src/shared/assets.d.ts". */
		types?: string;
	}

	/** The Roblox creator that owns uploaded assets. */
	export interface Creator {
		type: "user" | "group";
		id: number;
	}

	/** Configures ` + "`rotor asset sync`" + `. */
	export interface AssetsConfig {
		/** Glob patterns of asset files relative to the project root. */
		paths?: string[];
		output?: AssetsOutput;
		creator: Creator;
	}

	/** Publishes a built place file to a place id. */
	export interface PlaceDeploy {
		file: string;
		placeId: number;
	}

	/** Universe-level experience settings. */
	export interface ExperienceConfig {
		name?: string;
		description?: string;
		playability?: "public" | "private" | "friends";
	}

	/** A badge to create or update. */
	export interface Badge {
		name?: string;
		description?: string;
		icon?: string;
	}

	/** One named deploy target (e.g. "dev", "prod"). */
	export interface Environment {
		universeId?: number;
		places?: Record<string, PlaceDeploy>;
		experience?: ExperienceConfig;
		payments?: string;
		badges?: Record<string, Badge>;
	}

	/** Configures ` + "`rotor deploy`" + `. */
	export interface DeployConfig {
		environments?: Record<string, Environment>;
	}

	/** The shape of the object default-exported from rotor.config.ts. */
	export interface Config {
		assets?: AssetsConfig;
		deploy?: DeployConfig;
	}

	/** Identity helper that provides typing for the config object. */
	export function defineConfig(config: Config): Config;
}
`

// WriteTypeDeclarations writes rotor-config.d.ts into projectDir so editors
// can resolve the virtual "rotor/config" module.
func WriteTypeDeclarations(projectDir string) error {
	return os.WriteFile(filepath.Join(projectDir, TypeDeclarationsFileName), []byte(TypeDeclarations), 0o644)
}
