package config

import (
	"os"
	"path/filepath"
)

// TypeDeclarationsFileName is the file WriteTypeDeclarations writes.
const TypeDeclarationsFileName = "rotor-config.d.ts"

// TypeDeclarations is the ambient TypeScript declaration for the virtual
// config module ("@rotor-rbx/rotor", canonical; "rotor/config" and the
// /config subpath are aliases). It mirrors the Go structs in config.go 1:1
// and is what gives rotor.config.ts editor typing (written by `rotor init`,
// refreshed by any command when stale).
const TypeDeclarations = `// Generated by rotor. Do not edit; this file is refreshed automatically.
// Ambient types for the virtual config module used by rotor.config.ts.

declare module "@rotor-rbx/rotor" {
	/** Where generated asset modules are written. */
	export interface AssetsOutput {
		/** Output path of the generated Luau module, e.g. "src/shared/assets.luau". */
		luau?: string;
		/** Output path of the matching .d.ts, e.g. "src/shared/assets.d.ts". */
		types?: string;
	}

	/** The Roblox creator that owns uploaded assets. */
	export interface Creator {
		type: "user" | "group";
		id: number;
	}

	/** Configures ` + "`rotor asset sync`" + `. */
	export interface AssetsConfig {
		/** Glob patterns of asset files relative to the project root. */
		paths?: string[];
		output?: AssetsOutput;
		creator: Creator;
	}

	/** Publishes a built place file to a place id (and optionally manages place metadata). */
	export interface PlaceDeploy {
		file: string;
		placeId: number;
		name?: string;
		description?: string;
		maxPlayers?: number;
		versionType?: "saved" | "published";
	}

	/** Paid private servers; omit price for free private servers. */
	export interface PrivateServers {
		price?: number;
	}

	/** Universe-level experience settings. */
	export interface ExperienceConfig {
		name?: string;
		description?: string;
		playability?: "public" | "private" | "friends";
		privateServers?: PrivateServers;
	}

	/** A badge to create or update. */
	export interface Badge {
		name?: string;
		description?: string;
		icon?: string;
	}

	/** A game pass to create or update; omit price to leave it off sale. */
	export interface GamePass {
		name?: string;
		description?: string;
		price?: number;
		icon?: string;
	}

	/** A developer product to create or update. */
	export interface Product {
		name?: string;
		description?: string;
		price?: number;
	}

	/** A universe social link. */
	export interface SocialLink {
		title?: string;
		url?: string;
		type?: "facebook" | "twitter" | "youtube" | "twitch" | "discord" | "github" | "guilded";
	}

	/** One named deploy target (e.g. "dev", "prod"). */
	export interface Environment {
		universeId?: number;
		places?: Record<string, PlaceDeploy>;
		experience?: ExperienceConfig;
		payments?: string;
		badges?: Record<string, Badge>;
		gamePasses?: Record<string, GamePass>;
		/** Experience icon image path. */
		icon?: string;
		/** Ordered thumbnail image paths (max 10). */
		thumbnails?: string[];
		/** Developer products. */
		products?: Record<string, Product>;
		/** Universe social links. */
		socialLinks?: Record<string, SocialLink>;
	}

	/** Configures ` + "`rotor deploy`" + `. */
	export interface DeployConfig {
		environments?: Record<string, Environment>;
	}

	/** The shape of the object default-exported from rotor.config.ts. */
	export interface Config {
		assets?: AssetsConfig;
		deploy?: DeployConfig;
	}

	/** Identity helper that provides typing for the config object. */
	export function defineConfig(config: Config): Config;
}

declare module "@rotor-rbx/rotor/config" {
	export * from "@rotor-rbx/rotor";
}

declare module "rotor/config" {
	export * from "@rotor-rbx/rotor";
}
`

// WriteTypeDeclarations writes rotor-config.d.ts into projectDir so editors
// can resolve the virtual "rotor/config" module.
func WriteTypeDeclarations(projectDir string) error {
	_, err := RefreshTypeDeclarations(projectDir)
	return err
}

// RefreshTypeDeclarations writes rotor-config.d.ts into projectDir when the
// file is missing or its content is stale (differs from the current
// TypeDeclarations). The write is atomic (temp file + rename) so a concurrent
// editor/tsserver read never sees a half-written declaration. It reports
// whether the file was (re)written; an up-to-date file is left untouched.
func RefreshTypeDeclarations(projectDir string) (bool, error) {
	path := filepath.Join(projectDir, TypeDeclarationsFileName)
	if existing, err := os.ReadFile(path); err == nil && string(existing) == TypeDeclarations {
		return false, nil
	}
	if err := atomicWriteFile(path, []byte(TypeDeclarations)); err != nil {
		return false, err
	}
	return true, nil
}

// atomicWriteFile writes data to path via a temp file in the same directory
// plus a rename, so readers observe either the old or the new content.
func atomicWriteFile(path string, data []byte) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		os.Remove(tmpName)
		return err
	}
	return nil
}
